/*
@TargetNode='localhost'
@GeneratedBy=ove.aursland
@GenerationDate=01/27/2022 11:08:41
@GenerationHost=PF34SMD2
*/

instance of MSFT_MsiPackage as $MSFT_MsiPackage1ref
{
SourceInfo = "::7::9::MsiPackage";
 Path = "https://github.com/jeircul/msi/raw/master/googlechromestandaloneenterprise64.msi";
 ModuleVersion = "2.12.0.0";
 ModuleName = "PSDscResources";
 Ensure = "Absent";
 ResourceID = "[MsiPackage]Chrome";
 ProductId = "{9ABC27FD-AA4B-3C50-B76B-38FCFFCCDB03}";
 ConfigurationName = "InstallMSI";
};
instance of OMI_ConfigurationDocument

                    {
 Version="2.0.0";

                        MinimumCompatibleVersion = "1.0.0";

                        CompatibleVersionAdditionalProperties= {"Omi_BaseResource:ConfigurationName"};

                        Author="ove.aursland";

                        GenerationDate="01/27/2022 11:08:41";

                        GenerationHost="PF34SMD2";

                        Name="InstallMSI";

                    };
